server:
  port: 10087

spring:
  datasource:
    url: jdbc:mysql://10.17.38.203:3306/trsspider?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: trsspider
    password: gzXd7a3vguFkM94JoPS7

monitor:
  server:
    ip: 127.0.0.1
    # 需求 6 要求的监控端口列表
    ports: 9092,9100,10087
  kafka:
    script-path: "/data/TRS/kafka_2.13-2.8.0/bin/kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --list"
  alarm:
    email-to: 735543130@qq.com,1584521716@qq.com
    daily-limit:
      port: 5    # 新增：端口告警每天上限
      kafka: 3   # 新增：Kafka告警每天上限
  rules:
    data-stop-hours: 8 # 新增：断流几小时报警
    fail-level:
      l1: 20  # 新增：阶梯告警阈值
      l2: 50
      l3: 100